Repository kdt-final-3/salarying-be, pull requests merged in 2023-04, with the labels that each got.

#80 feat: 인재관리 서비스의 조회 관련 기능 개발 (전체지원자 조회, 단계별 지원자 조회) - #67
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#83 feat: 인재관리 서비스 채용단계 변경 및 합격/불합격 처리 기능 구현 - #68
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#84 feat: 인재관리 서비스의 인재현황 관련 기능 개발 - #69
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/CountAndDateResponseDTO.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#85 feat: 인재 상세페이지 서비스의 지원자 상세 조회 기능 개발 - #70
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/CertificateResponseDTO.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/entity/apply/Activities.java
  src/main/java/com/finalproject/recruit/entity/apply/Awards.java
  src/main/java/com/finalproject/recruit/entity/apply/Career.java
  src/main/java/com/finalproject/recruit/entity/apply/Certificate.java
  src/main/java/com/finalproject/recruit/entity/apply/Education.java
  src/main/java/com/finalproject/recruit/entity/apply/Language.java
  src/main/java/com/finalproject/recruit/entity/apply/Military.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#86 feat: 인재 상세페이지 서비스 개발 (지원자 코멘트 등록, 찜하기, 탈락인재 보관함 이동) - #71,#72
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#87 feat: 인재 상세페이지 서비스 (지원자 서류검토 처리, 면접일자 지정) - #73
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#97 feat : 회원 가입 시 이메일 인증 API 구현 - #96
  src/main/java/com/finalproject/recruit/controller/MemberController.java
  src/main/java/com/finalproject/recruit/dto/member/MemberReqDTO.java
  src/main/java/com/finalproject/recruit/service/MemberService.java
Labels: For: API, For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#98 refactor: 전체 지원자 조회 시 키워드 우대가점,키워드 리스트 반환 추가 및 병역사항 관련 내용 삭제
  src/main/java/com/finalproject/recruit/dto/applicant/ApplicationReq.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/entity/Keyword.java
  src/main/java/com/finalproject/recruit/entity/apply/Military.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryCategory.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryClass.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryDivision.java
  src/main/java/com/finalproject/recruit/repository/apply/MilitaryRepository.java
  src/main/java/com/finalproject/recruit/service/ApplicantService.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: High, Status: Completed

#101 refactor: 인재 상세페이지 서비스 - 면접일 지정 API 수정 (파라미터 변경)
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#103 feat: 알림센터, 탈락인재 보관함 로그인 로직 추가 - #93
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/controller/KeepController.java
  src/main/java/com/finalproject/recruit/controller/NoticeController.java
  src/main/java/com/finalproject/recruit/dto/keep/ApplicantsRes.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#106 feat: 탈락인재 지원자 검색 api 추가 - #107
  src/main/java/com/finalproject/recruit/controller/KeepController.java
  src/main/java/com/finalproject/recruit/dto/keep/ApplicantsRes.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplicantService.java
  src/main/java/com/finalproject/recruit/service/KeepService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#112 hotfix : appspec.yml 수정 - overwrite
  appspec.yml
Labels: Type: Config, For: CI/CD, Priority: High, Status: In Progress

#113 hotfix : main.yml 파일 수정
  .github/workflows/main.yml
Labels: Type: Config, For: CI/CD, Priority: High, Status: In Progress

#114 fix : SecurityConfig 수정 - 이메일 인증 권한 검사 허용
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
Labels: For: Backend, Priority: Medium, Status: In Progress, Type : Bug

#115 refactor: 인재관리 서비스 - 채용단계별 지원자 조회 로직 수정
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#118 fix : SecurityConfig 수정 - 이메일 중복검사 권한 허용
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
Labels: For: Backend, Priority: Medium, Status: In Progress, Type: Feature

#119 Release : 수정 사항 반영
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/controller/RecruitController.java
  src/main/java/com/finalproject/recruit/dto/member/MemberResDTO.java
  src/main/java/com/finalproject/recruit/exception/member/ErrorCode.java
  src/main/java/com/finalproject/recruit/jwt/JwtManager.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/repository/MemberRepository.java
  src/main/java/com/finalproject/recruit/repository/RecruitRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
  src/main/java/com/finalproject/recruit/service/MemberService.java
  src/main/java/com/finalproject/recruit/service/RecruitService.java
Labels: For: Backend

#120 fix : 지원자 검색 API 수정
  src/main/java/com/finalproject/recruit/service/NoticeService.java
Labels: For: API, Priority: Medium, Status: In Progress, Type: Feature

#121 Refactor : 매핑 타입 및 URL 변경
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/controller/MemberController.java
Labels: Type: Config, Type: Refactoring, For: Backend, Priority: Medium

#122 refactor: 지원자 상세조회 리턴값 변경
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#125 fix : 이메일 전송 내역 저장 로직 수정
  src/main/java/com/finalproject/recruit/service/NoticeService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#126 refactor: 인재 상세페이지 서비스 - 지원자 상세 조회 시 리턴 값 수정
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#130 refactor: 채용단계별 디데이 리턴값 수정
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#131 refactor: 면접일 지정 API 파라미터 RequestBody로 받는 것으로 수정
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/MeetingDateReq.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#132 refactor: 인재 코멘트 등록 파라미터 수정
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/EvaluationReq.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Low, Status: Completed

#133 Release : 3차 수정 사항 적용
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/EvaluationReq.java
  src/main/java/com/finalproject/recruit/dto/applymanage/MeetingDateReq.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Medium, Status: Completed

#134 refactor: Apply 엔티티 Military 컬럼 중복 내용 삭제
  src/main/java/com/finalproject/recruit/dto/applicant/ApplicationReq.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyDetailResponseDTO.java
  src/main/java/com/finalproject/recruit/dto/applymanage/CertificateResponseDTO.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
Labels: Type: Refactoring, For: Backend, Priority: Low, Status: Completed

#135 refactor: 인재관리 서비스 - 지원자 채용단계 변경 API 수정
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyProcedureReq.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
Labels: Type: Refactoring, For: API, Priority: Medium, Status: Completed

#136 feat: 탈락인재 보관함 이동 / 해제 일괄 처리 기능 개발
  src/main/java/com/finalproject/recruit/controller/ApplyManageController.java
  src/main/java/com/finalproject/recruit/controller/KeepController.java
  src/main/java/com/finalproject/recruit/dto/applymanage/ApplyIdsReq.java
  src/main/java/com/finalproject/recruit/exception/keep/ErrorCode.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
  src/main/java/com/finalproject/recruit/service/KeepService.java
Labels: For: API, Priority: Medium, Status: Completed, Type: Feature

#137 test: 테스트 코드 추가
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/ApplyManageService.java
  src/test/java/com/finalproject/recruit/service/ApplyManageServiceTest.java
  src/test/java/com/finalproject/recruit/service/CalcKeywordTest.java
Labels: Type: Refactoring, Type: Test, For: API, Priority: Medium, Status: Completed

#138 feat: 가장 최근 사용한 채용폼 상세조회 (Redis 이용 - 성능개선 목적)
  src/main/java/com/finalproject/recruit/config/RedisConfig.java
  src/main/java/com/finalproject/recruit/controller/RecruitController.java
  src/main/java/com/finalproject/recruit/repository/RecruitRepository.java
  src/main/java/com/finalproject/recruit/service/RecruitService.java
Labels: For: API, Priority: High, Status: Completed, Type: Feature

#139 refactor : redis 캐시 적용한 채용폼 조회, 수정 api 추가
  build.gradle
  src/main/java/com/finalproject/recruit/config/CacheConfig.java
  src/main/java/com/finalproject/recruit/controller/RecruitController.java
  src/main/java/com/finalproject/recruit/dto/recruit/RecruitRes.java
  src/main/java/com/finalproject/recruit/service/RecruitService.java
Labels: For: Backend, Priority: Medium, Status: Completed, Type: Feature
