Repository kdt-final-3/salarying-be, pull requests merged in 2023-03, with the labels that each got.

#2 conf : edit .gitignore
  .gitignore
Labels: config, docs

#12 conf: main.yml 수정
  .github/workflows/main.yml
Labels: For: CI/CD, Priority: Medium, Status: Completed

#32 feat : Entity 설정 - #15
  .github/workflows/main.yml
  build.gradle
  src/main/java/com/finalproject/recruit/RecruitApplication.java
  src/main/java/com/finalproject/recruit/config/RedisConfig.java
  src/main/java/com/finalproject/recruit/config/SecurityConfig.java
  src/main/java/com/finalproject/recruit/dto/UserResDTO.java
  src/main/java/com/finalproject/recruit/entity/Apply.java
  src/main/java/com/finalproject/recruit/entity/Keyword.java
  src/main/java/com/finalproject/recruit/entity/Member.java
  src/main/java/com/finalproject/recruit/entity/Recruit.java
  src/main/java/com/finalproject/recruit/entity/apply/Activities.java
  src/main/java/com/finalproject/recruit/entity/apply/Awards.java
  src/main/java/com/finalproject/recruit/entity/apply/Career.java
  src/main/java/com/finalproject/recruit/entity/apply/Certificate.java
  src/main/java/com/finalproject/recruit/entity/apply/Education.java
  src/main/java/com/finalproject/recruit/entity/apply/Language.java
  src/main/java/com/finalproject/recruit/entity/apply/Military.java
  src/main/java/com/finalproject/recruit/entity/apply/Resume.java
  src/main/java/com/finalproject/recruit/jwt/JwtAuthenticationFilter.java
  src/main/java/com/finalproject/recruit/jwt/JwtTokenProvider.java
  src/main/java/com/finalproject/recruit/parameter/ApplyProcedure.java
  src/main/java/com/finalproject/recruit/parameter/EduStatus.java
  src/main/java/com/finalproject/recruit/parameter/EduYear.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryCategory.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryClass.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryDivision.java
  src/main/java/com/finalproject/recruit/util/BaseTime.java
Labels: For: Backend, Priority: Critical, Status: In Progress, Type: Feature

#51 Refactor : Refactor Auth part method & token
  src/main/java/com/finalproject/recruit/dto/member/MemberReqDTO.java
  src/main/java/com/finalproject/recruit/dto/member/MemberResDTO.java
  src/main/java/com/finalproject/recruit/entity/Member.java
  src/main/java/com/finalproject/recruit/jwt/JwtTokenProvider.java
  src/main/java/com/finalproject/recruit/repository/MemberRepository.java
  src/main/java/com/finalproject/recruit/service/MemberService.java
Labels: Type: Refactoring, For: Backend, Priority: High, Status: In Progress

#78 feat: 단체 이메일 전송 api
  build.gradle
  src/main/java/com/finalproject/recruit/dto/notice/EmailReq.java
  src/main/java/com/finalproject/recruit/parameter/EduStatus.java
  src/main/java/com/finalproject/recruit/parameter/MilitaryEnum.java
  src/main/java/com/finalproject/recruit/repository/ApplyRepository.java
  src/main/java/com/finalproject/recruit/service/NoticeService.java
Labels: For: API, Priority: High, Status: In Progress, Type: Feature
